export const Industries = [
  'Food & Beverage',
  'Retail',
  'Health & Beauty',
  'Fashion',
  'Home & Garden',
  'Technology',
  'Art & Crafts',
  'Fitness & Wellness',
  'Automotive',
  'Professional Services',
  'Education & Training',
  'Entertainment',
  'Travel & Tourism',
  'Pets & Animals',
  'Finance',
  'Events & Occasions',
  'Real Estate',
  'Consulting',
  'Hospitality',
  'Photography & Videography',
  'Childcare & Babysitting',
  'Cleaning Services',
  'Legal Services',
  'Marketing & Advertising',
  'Construction & Renovation',
  'Music & Performing Arts',
  'Sports & Recreation',
  'Transportation',
  'Wedding Services',
  'Food Delivery',
  'Gardening & Landscaping',
  'Insurance',
  'Beauty & Spa',
  'Online Services',
  'Printing & Publishing',
  'Repair & Maintenance',
  'Security Services',
  'Software Development',
  'Tailoring & Alterations',
  'Writing & Editing',
  'E-commerce',
  'Home Appliances',
  'Interior Design',
  'Language Services',
  'Logistics',
  'Manufacturing',
  'Medical Services',
  'Nutrition & Diet',
  'Packaging Services',
  'Social Media Management',
  'Tutoring Services',
  'Web Design & Development',
];
